### PR TITLE
Remove  $default_options variable and leave the merging up to Hiera.

### PR DESCRIPTION
**Pull request by bschonec**

### CODE REVIEW

**Comment by joshbeard** [comment]
Thanks, @bschonec. I do want to do this, but we'll have to resolve the issue with the Suse default options - they're not supposed to be merged. It might be simpler to just ditch the merging and be explicit in the `osfamily-X` data, leaving the `osfamily` data as a fallback if a specific version isn't specified.

**Comment by bschonec** [comment]
Ah, heck.  I didn't even consider what common.yaml would do to the non-RHEL servers.  Good catch.  I'll see if I can fix that, too.

**Comment by bschonec** [comment]
I'm coming back to this now after learning a bit about spec test writing.  When you say that the Suse default options shouldn't be merged, are you saying that the Suse stuff shouldn't be merged with the stuff that's in common.yaml?  I'd like to update this module as I find it quite useful.  What is it about the Suse stuff that makes it different than RedHat?

**Comment by joshbeard** [comment]
Hey @bschonec, good to hear back! I recently merged https://github.com/joshbeard/puppet-login_defs/pull/43 which deprecates the `common_options` parameter and discontinues using it in the data files.

I also simplified them a little to be more explicit and less confusing about merging (I hope, anyway).

That might have solved some of what this PR was going after, but let me know what you think.

**Comment by bschonec** [comment]
Well, fantastic!  The reason this has come back to life is that I've made some very small progress with SPEC testing in Puppet and I revisited some simple updates to project that I use regularly.

**Pull request closed without merging**
